config/routes.rb
Vintenews::Application.routes.draw do
  get 'login' => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'
  get 'register' => 'users#new'
  get 'about' => 'pages#about'
  get 'lists' => 'pages#lists'

  resource :user_session
  resources :comments
  resources :posts
  get 'vote' => 'votes#create'

  resources :users do
    resources :posts
    resources :comments
  end

  resources :posts do
    resources :comments
  end

  root :to => "posts#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_voteable
    
  belongs_to :parent, :class_name => "Comment", :foreign_key => :parent_id
  has_many :sub_comments, :class_name => "Comment", :foreign_key => :parent_id
  belongs_to :post
  belongs_to :user
  #has_karma :posts
  
  validates :user_id, :presence => true
  validates :post_id, :presence => true
  validates :body, :presence => true, :length => { :within => 2..10000 }
  
  default_scope where(:status => nil)

  scope :top_level, lambda {  where("comments.parent_id IS NULL") }
  scope :latest, order("created_at DESC")
  scope :last_100, order("created_at DESC").limit(100)
  
  def mark_as_deleted
    self.status = "deleted"
    self.save
  end
  
  def votes_count
    votes = votes_for      
    if self.sub_comments.count > 0 
      votes += eval(self.sub_comments.map(&:votes_for).join("+"))
    end
    
    #while       
    #  votes + votes_count
    #end
    
    votes
  end
  
end

# == Schema Information
#
# Table name: comments
#
#  id         :integer(4)      not null, primary key
#  post_id    :integer(4)
#  user_id    :integer(4)
#  body       :text
#  created_at :datetime
#  updated_at :datetime
#  parent_id  :integer(4)
#  status     :string(255)
#

app/controllers/comments_controller.rb
# encoding: utf-8
class CommentsController < ApplicationController
  before_filter :find_or_create_comment, :except => [:index, :destroy]
  before_filter :require_user, :except => [:show, :index]
  
  def index
    respond_to do |format|      
      if params[:user_id]
        @comments = User.find_by_login(params[:user_id]).comments
      else
        @comments = Comment.last_100
      end
      format.html 
      format.rss {
        @comments = Comment.last_100
      }
    end
    
    
  end
    
  def show  
  end
  
  def new
  end
  
  def create
    if params[:link].blank?
      respond_to do |format|
        if @comment.save
          format.html { redirect_to(@post) }
          format.xml  { render :xml => @comment, :status => :created, :location => @post }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
        end
      end
    else 
      flash[:error] = I18n.t("messages.spammer")
      redirect_to root_path
    end  
  end
  
  def destroy
    if current_user.try(:admin?)
      @comment = Comment.find(params[:id])
      @comment.mark_as_deleted
    end
    redirect_to @comment.post
  end
  
  protected
    def find_or_create_comment
      if params[:post_id]
        @post = Post.find(params[:post_id])
      end
      if params[:id]
        @comment = Comment.find(params[:id])
        @sub_comment = @comment.sub_comments.new
      else
        @comment = @post.comments.build(params[:comment])
        @comment.user = current_user
      end
    end
  
end

app/views/comments/_comment.html.haml
- comment = comment.nil? ? @comment : comment
.comment{:id => "comment-#{comment.id}"}
  %span.arrow
    = link_to image_tag("arrow-blue.png"), vote_path(:comment_id => comment.id) unless current_user && current_user.voted_for?(comment)
  .faded
    = pluralize(comment.votes_count, I18n.t('posts.point'))
    = I18n.t('comments.submitted_by')
    = link_to comment.user.login, user_path(comment.user)
    = I18n.t('posts.posted_on')
    %span.relative_post_date
      = comment.created_at.to_formatted_s(:rfc822)
    = I18n.t('comments.since')
    |
    = link_to I18n.t('comments.link'), post_comment_path(comment.post, comment)
    - if request.url != post_url(comment.post)
      |
      = link_to I18n.t('comments.parent'), post_path(comment.post)
      |
      = "#{I18n.t("comments.news")}:"
      = link_to truncate(comment.post.title, :length => 35), post_path(comment.post)
    - if current_user.try(:admin?)
      |
      = link_to "Delete", comment_path(comment), :method => :delete, :confirm => I18n.t("comments.delete_confirmation")

  %div.comment_body
    = sanitize(line_break(comment.body), :tags => %w(ul li img strong br p b) )
  
    - if request.url != comment_url(comment)
      %div.reply_link
        = link_to I18n.t("comments.reply"), comment_path(comment)
    - else
      = render "comments/form"
%br

%div.sub_comment
  = render :partial => "comments/comment", :collection => comment.sub_comments

app/views/comments/_form.html.haml
- @post = @post.nil? ? @comment.post : @post
- @this_comment = @comment.new_record? ? @comment : @sub_comment # handle sub_comments

= form_for @this_comment, :url => post_comments_path(@post)  do |f|
 
  - if @this_comment.errors.any?
    %ul
      - @this_comment.errors.full_messages.each do |msg|
        %li= msg        
  %br   
  %div
    = f.text_area :body, {:cols => "90", :rows => "10"}
    = f.hidden_field :parent_id, :value => @comment.id
  = render 'layouts/spammer_check'
  %div  
    = f.submit I18n.t('comments.add_comment'), :disable_with => t("common.button_disable_with")

app/views/comments/index.html.haml
%h2
  = I18n.t('comments.comments')
= render :partial => "comment", :collection => @comments

app/views/comments/new.html.haml
= render "form"

app/views/comments/show.html.haml
= content_for :title do
  = @comment.post.title

%h2
  = I18n.t('comments.comments')
= render :partial => "comment"