config/routes.rb
Vintenews::Application.routes.draw do
  get 'login' => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'
  get 'register' => 'users#new'
  get 'about' => 'pages#about'
  get 'lists' => 'pages#lists'

  resource :user_session
  resources :comments
  resources :posts
  get 'vote' => 'votes#create'

  resources :users do
    resources :posts
    resources :comments
  end

  resources :posts do
    resources :comments
  end

  root :to => "posts#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter

  has_many :posts
  has_many :comments
  has_karma :posts

  validates :login,  :presence => true
  validates :password, :presence => true, :on => :create

  acts_as_authentic do |c|
    c.require_password_confirmation = false
    c.merge_validates_format_of_email_field_options :message => I18n.t('user_model.validations.email_format')
    c.merge_validates_format_of_login_field_options :message => I18n.t('user_model.validations.login_format')
  end

  def to_param
    login
  end
  
  def admin?
    login == "brupm" || login == "ibias" || login == "daviscabral" || login == "roberto" || login == "ozeias"
  end
end


# == Schema Information
#
# Table name: users
#
#  id                :integer(4)      not null, primary key
#  login             :string(255)
#  email             :string(255)
#  crypted_password  :string(255)
#  password_salt     :string(255)
#  persistence_token :string(255)
#  login_count       :integer(4)
#  last_login_at     :datetime
#  current_login_ip  :string(255)
#  last_login_ip     :string(255)
#  created_at        :datetime
#  updated_at        :datetime
#  about             :text
#

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_user, :except => [:new, :create, :show]

  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.haml
      format.xml  { render :xml => @user }
    end
  end

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_back_or_default(root_path) 
          flash[:notice] = I18n.t('users_controller.messages.user_created')
        }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @user = current_user

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { 
          flash[:notice] = I18n.t('users_controller.messages.user_updated')
          render :action => "show" 
        }
        format.xml  { head :ok }
      else
        format.html { render :action => "show" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def show
    @user = User.find_by_login(params[:id])
  end

  def destroy
    @user = current_user
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
  
end

app/views/users/_edit_form.html.haml
= form_for @user do |f|
  
  - if @user.errors.any?
    %ul
      - @user.errors.full_messages.each do |msg|
        %li= msg        
        
  %div
    = f.label :email
    %br
    = f.text_field :email
  %div
    = f.label :change_password, I18n.t('users.new_password')
    %br
    = f.password_field :password
  %div
    = f.label :about, I18n.t('users.about')
    %br
    = f.text_area :about, {:cols => "90", :rows => "10"}
  %div  
    = f.submit I18n.t('users.save'), :disable_with => t("common.button_disable_with")

app/views/users/_form.html.haml
= form_for @user do |f|
  
  - if @user.errors.any?
    %ul
      - @user.errors.full_messages.each do |msg|
        %li= msg        
        
  %div
    = f.label :login, I18n.t('users.login')
    %br
    = f.text_field :login
  %div
    = f.label :email
    %br
    = f.text_field :email
  %div
    = f.label :password, I18n.t('users.password')
    %br
    = f.password_field :password
  %div  
    = f.submit I18n.t('users.register'), :disable_with => t("common.button_disable_with")

app/views/users/new.html.haml
%h1
  = I18n.t('users.register').capitalize

= render 'form'

app/views/users/show.html.haml
%h1
  = @user.login
%p
  = "#{I18n.t('users.created')}: #{@user.created_at.to_formatted_s(:short_ordinal)}"
  %br
  = "#{I18n.t('users.karma')}: #{@user.karma}"
  %br
  = "#{I18n.t('users.login_count')}: #{@user.login_count}"
  %br
  = link_to "#{I18n.t('users.posts')} (#{@user.posts.count})", user_posts_path(@user)
  %br
  = link_to "#{I18n.t('users.comments')} (#{@user.comments.count})", user_comments_path(@user)
  
%p
  - if @user == current_user
    %p
      = render 'edit_form'
  - else 
    %p     
      = @user.about