config/routes.rb
Vintenews::Application.routes.draw do
  get 'login' => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'
  get 'register' => 'users#new'
  get 'about' => 'pages#about'
  get 'lists' => 'pages#lists'

  resource :user_session
  resources :comments
  resources :posts
  get 'vote' => 'votes#create'

  resources :users do
    resources :posts
    resources :comments
  end

  resources :posts do
    resources :comments
  end

  root :to => "posts#index"
end

app/views/layouts/_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-2885985-23']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_header.html.haml
%a{:href => "/"}
  %img{:src => "/images/logo-mini.png", :style => "float: left; padding-right: 10px;"}
%p
  = link_to I18n.t('layouts.most_popular'), root_path 
  |
  = link_to I18n.t('layouts.recent'), root_path(:order => "latest") 
  |
  = link_to I18n.t('layouts.comments'), comments_path
  |
  %strong 
    = link_to I18n.t('layouts.submit_news'), new_post_path
  %span{:style => "float:right;"}
    - if current_user
      = link_to "#{I18n.t('layouts.edit_profile')} (#{current_user.login})", user_path(current_user)
      |
      = link_to I18n.t('layouts.logout'), logout_path 
    - else
      = link_to I18n.t('layouts.register'), register_path 
      |
      = link_to I18n.t('layouts.login'), login_path

app/views/layouts/_spammer_check.html.haml
%span{:style => "display:none;"}
  = text_field_tag :link

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title 
      = (yield :title).blank? ? 'VinteNews - Notícias para Hackers' : (yield :title)
    %meta{'http-equiv' => 'Content-Type', :content => 'text/html', :charset => 'UTF-8'}/
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'jquery.min.js', 'rails.js', "date.extensions.js", "application.js"
    = csrf_meta_tag
    = auto_discovery_link_tag(:rss, { :controller => "posts", :action => "index", :format => :rss })
    = render :partial => "layouts/analytics"
  %body
    #container
      #content
        #header
          = render :partial => "layouts/header"
        #main-content
          - flash.each do |k,v|
            %p{:class => k}= v

          = yield
        #footer
          %p
            = link_to I18n.t('layouts.lists'), lists_url
            |
            = link_to I18n.t('layouts.about_this_site'), about_url
            |
            = link_to "Twitter", "http://twitter.com/vintenews"
            |
            = link_to "RSS", posts_url(:format => :rss)
            |
            = link_to "#{I18n.t("layouts.comments")} RSS", comments_url(:format => :rss)
            | Bookmarklet:
            = link_to "+VinteNews", "javascript:location.href='http://#{request.host}/posts/new?title='+encodeURIComponent(document.title)+'&url='+encodeURIComponent(location.href)"                        
            